### ISSUE TITLE
[evm] create collection doesn't raise any log

### ISSUE THREAD

**Issue by asiniscalchi** [freeverseio/laos-ownership-node#136]
using `remix` the log of create collection seems to not be fired. 
polkadot.js shows the evm.log event correctly.

It seems the behavior is dependent from the fake bytecode injected in the contract address on genesis: executing the tx using a node previous to the bytecode injection raises the log.

**Comment by asiniscalchi** [comment]
we don't care about the `possible remix bugs` we are happy with web3,js or whatever broadly used client be able to capture the log

**Comment by magecnion** [comment]
![Image](https://github.com/freeverseio/laos-ownership-node/assets/5495235/1f27a231-ab24-48e9-829b-f0144975ad67)

**Comment by tonimateos** [comment]
QA completed on arrakis

**Comment by tonimateos** [comment]
Merge done
