### ISSUE TITLE
As a LAOS bridge dev I want to create a local implementation of the bridge between Own-EvoChains so I can clarify the work that will be required

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos-ownership-node#19]
Note: this is the candidate codebase for Substrate/GRANDPA chains - https://github.com/paritytech/parity-bridges-common#running-the-bridge 
Also check: https://github.com/paritytech/parity-bridges-common/tree/master/relays/parachains

ACCEPTANCE:

* It is possible to show the bridge running locally using the separate solochains as in the demo
* Brief documentation is produced explaining what is needed to facilitate the integration in our system, such as what pallets are involved, etc. In particular, understand if it can apply to the Ownchain, which *inherits* GRANDPA finality from the relay chain.
* Find out the best contacts to ask technical questions about the bridge

```[tasklist]
### SUBTASKS
- [x] run locally
- [x] investigate code to find out what is needed for LAOS
```

**Comment by asiniscalchi** [comment]
https://substrate.stackexchange.com/questions/8315/bridge-substrate-solo-chain-to-parachain
https://substrate.stackexchange.com/questions/9079/how-to-send-xcm-message-from-parachain-to-solochain-via-the-parity-bridge

**Comment by asiniscalchi** [comment]
https://substrate.stackexchange.com/questions/9149/solochain-parachain-bridge
