### ISSUE TITLE
As a dev I want Clippy to be added to CI/CD so the code follows default convetions

### ISSUE THREAD

**Issue by dastanfv** [freeverseio/laos-ownership-node#20]
It helps us to follow Rust code conventions, make our code more readable and debuggable.

ACCEPTANCE:

* Clippy doesn't fail, based on the default settings, and is integrated in our CI.

**Comment by asiniscalchi** [comment]
https://github.com/freeverseio/pallet-livingassets-ownership/pull/6

**Comment by dastanfv** [comment]
https://github.com/freeverseio/pallet-livingassets-ownership/pull/6

**Comment by dastanfv** [comment]
https://github.com/freeverseio/laos-evolution-node/pull/31
