### ISSUE TITLE
Executable to be laos instead of parachain-template-node

### ISSUE THREAD

**Issue by dastanfv** [freeverseio/laos-ownership-node#22]
We should remove everything related to `substrate-parachain-template` that we forked from

**Comment by asiniscalchi** [comment]
We are still inheriting the name of the binary from the source repository : parachain-template-node ..

We want to change it to a better name aka: **laos**

**ACCEPTACE CRITERIA**
- I can run the node as 
```bash
$ laos --chain arrakis
```

**Comment by asiniscalchi** [comment]
**WARNING**: the database path contains the binary name => a sync from scratch of the blockchain will be triggered
