### ISSUE TITLE
As a MMask user of LAOS I want to connect MMask to the ownership chain so I can connect using my favourite wallets

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos-ownership-node#25]
ACCEPTANCE:

* I can configure MMask with the correct chainID and using a public Ownership node,
* it fails if the chainId is misconfigured
* the balance I get is correctly 0 set to zero

- [x] #35
- [x] transfer sudo to Ale
- [x] add eth rpc endpoint
- [x] #40  (Ale)
- [x] #41 (dastan)
- [x] create new parachain
- [ ] #62

**Comment by magecnion** [comment]
Two issues have arised developing this task:
- #35 
- #37 

Please merge them before facing the actual task
