### ISSUE TITLE
Ownership node doesn't sync using dev branch

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos-ownership-node#26]
ACCEPTANCE:

* the node syncs
* a test is added that verifies the hash of the genesis block

**Comment by asiniscalchi** [comment]
![Image](https://github.com/freeverseio/laos-ownership-node/assets/2387339/7f39a385-7102-4405-a13e-339c7e198b55)

**Comment by asiniscalchi** [comment]
removing the Acceptance criteria requiring the test. The error is about the storing format of the chain_specs
