### ISSUE TITLE
As a MMask user of LAOS I want to transfer funds in the ownership chain with MMask so I can keep using my favourite wallets

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos-ownership-node#42]
ACCEPTANCE:

* I can transfer funds using MMask from one account to another, connecting MMask to a public Ownership node
   * Toni asks Ale for his web3 address. Ale goes to his MMask and copy-pastes his address, and sends it to Toni
   * Toni clicks "send" in MMask, pastes Ale's address, and funds are transferred as expected, showing in Ale's MMask.

* Document how to add the network to MMask, in the README.md

**Comment by asiniscalchi** [comment]
https://github.com/freeverseio/laos-ownership-node/pull/60
