### ISSUE TITLE
As a dev I want CI parallelization and caching so that it's faster

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos-ownership-node#55]
ACCEPTANCE

* CI finishes significantly faster than before (previously, above 1h40m)
* #52

**Comment by asiniscalchi** [comment]
https://github.com/freeverseio/laos-ownership-node/actions/runs/5545786832



![Image](https://github.com/freeverseio/laos-ownership-node/assets/2387339/09b2b74a-cc19-4519-b3fe-e5c614e616ff)

**Comment by asiniscalchi** [comment]
https://github.com/freeverseio/laos-ownership-node/pull/59
