### ISSUE TITLE
Use new workspace dependencies feature

### ISSUE THREAD

**Issue by dastanfv** [freeverseio/laos-ownership-node#63]
context: https://doc.rust-lang.org/cargo/reference/workspaces.html#the-dependencies-table

**Comment by asiniscalchi** [comment]
It seems all the rust proyect are moving toward this pattern of dependency decalration.
So we will follow.

**ACCEPTANCE CRITERIA**:
- All the dependecy are declared in the root Cargo.toml

**Comment by dastanfv** [comment]
closed after #77
