### ISSUE TITLE
As a user of LAOS I want an upgrade of the runtime at the end of Sprint 3, to enjoy the added value in the live environment

### ISSUE THREAD

**Issue by asiniscalchi** [freeverseio/laos-ownership-node#80]
ACCEPTANCE:

* You can use the EVM explorer to use the pre-compiled contract

* [x] Reproduce the production environment locally and do the runtime upgrade locally
* [x] Actually do the runtime upgrade on the production

**Comment by dastanfv** [comment]
runtime upgrade succeeded.

<img width="1719" alt="Success runtime upgrade" src="https://github.com/freeverseio/laos-ownership-node/assets/137785454/d9433dd3-2b05-4886-9e19-fb115f16fd1a">

At first I generated the wasm with:

```bash
./target/release/laos export-genesis-wasm --chain arrakis > new-runtime.wasm
```

But apparently it is WRONG. Correct way is this:

```bash
./target/release/laos export-genesis-wasm > new-runtime.wasm
```

I assume if we pass the `--chain arrakis` argument it simply copies `:code` from the chain spec to the `new-runtime.wasm`, meaning it will copy runtime code from genesis.

**Comment by asiniscalchi** [comment]
```
$ cargo build --release --package laos-runtime
```
