### ISSUE TITLE
Make EVM createCollection method work with Truffle

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos-ownership-node#91]
As a user of LAOS that uses EVM wallets, I want to be able to use Truffle or Remix on contracts that use the current precompiled contract, so that all EVM tools work well with LAOS

----------
From Moonbeam former developer

![Image](https://user-images.githubusercontent.com/2387339/256469818-c0c60cf9-458a-44af-95f4-d0a72bf6a8f2.png)
----------

https://github.com/moonbeam-foundation/moonbeam/blob/61647d84124c8e6d099176ce5ba357f821204864/node/service/src/chain_spec/moonbase.rs#L245-L285

It is OK if we need a different precompiled contract and we stop using the previous one.

ACCEPTANCE

* I can use truffle to execute the createCollection precompiled contract
* I can deploy a smart contract that internally calls the precompiled contract, and execute it.

**Comment by tonimateos** [comment]
We probably need this: https://docs.moonbeam.network/builders/pallets-precompiles/precompiles/registry/

**Comment by asiniscalchi** [comment]
![Image](https://github.com/freeverseio/laos-ownership-node/assets/2387339/5efb4a0d-e79e-4914-b6c3-f502df384fec)
