### ISSUE TITLE
Add bridge GRANDPA pallet to ownership-parachain

### ISSUE THREAD

**Issue by tonimateos** [freeverseio/laos-ownership-node#94]
As a LAOS bridge relayer I want an integration of the GRANDPA finality pallet in the Ownchain, so I can relay data from the Evochain

Reuse research done in this previous User Story: https://github.com/freeverseio/laos-ownership-node/issues/19

ACCEPTANCE:

* There is an extrinsics method that allows the submission of EvoChain state roots alongside proof of finality in the Ownchain.
* A new state root is not accepted unless the proof of validity is correct, that it is signed by enough validators; the demo must show that it is not possible to lie
* We don't proof in this UStory that a correct one is accepted

**Comment by asiniscalchi** [comment]
related: https://github.com/freeverseio/laos-ownership-node/issues/19
